TEXTS = {
    "pl": {
        "welcome": "Dzień dobry! Wypełnij krótką ankietę, a nasz menedżer skontaktuje się z Tobą.",
        "ask_name": "Podaj imię i nazwisko:",
        "name_invalid": "Wpisz imię i nazwisko, co najmniej 2 wyrazy.",
        "ask_phone": "Udostępnij swój numer telefonu przyciskiem poniżej:",
        "share_phone": "📱 Udostępnij numer telefonu",
        "phone_invalid": "Użyj przycisku „Udostępnij numer telefonu”.",
        "ask_email": "Podaj adres e-mail:",
        "email_invalid": "Adres e-mail wygląda nieprawidłowo. Spróbuj ponownie.",
        "ask_city": "Wybierz miasto pracy:",
        "city": "📍 Warszawa",
        "success": "Dziękujemy! Twoje zgłoszenie zostało wysłane. Menedżer skontaktuje się z Tobą.",
        "already": "Masz już wysłane zgłoszenie. Czy chcesz wysłać nowe?",
        "again": "🔄 Wypełnij ponownie", "cancel": "Anuluj",
        "cancelled": "Pozostawiono poprzednie zgłoszenie.",
        "error": "Wystąpił błąd podczas wysyłania. Spróbuj ponownie później.",
    },
    "ua": {
        "welcome": "Вітаємо! Заповніть коротку анкету, і наш менеджер зв’яжеться з вами.",
        "ask_name": "Введіть ім’я та прізвище:",
        "name_invalid": "Введіть ім’я та прізвище, щонайменше 2 слова.",
        "ask_phone": "Надішліть свій номер телефону кнопкою нижче:",
        "share_phone": "📱 Надіслати номер телефону",
        "phone_invalid": "Скористайтеся кнопкою «Надіслати номер телефону».",
        "ask_email": "Введіть вашу електронну адресу:",
        "email_invalid": "Електронна адреса виглядає неправильно. Спробуйте ще раз.",
        "ask_city": "Оберіть місто роботи:", "city": "📍 Варшава",
        "success": "Дякуємо! Вашу заявку надіслано. Менеджер зв’яжеться з вами.",
        "already": "Ви вже надсилали заявку. Бажаєте заповнити нову?",
        "again": "🔄 Заповнити знову", "cancel": "Скасувати",
        "cancelled": "Попередню заявку залишено без змін.",
        "error": "Сталася помилка під час надсилання. Спробуйте пізніше.",
    },
    "ru": {
        "welcome": "Здравствуйте! Заполните короткую анкету, и наш менеджер свяжется с вами.",
        "ask_name": "Введите имя и фамилию:",
        "name_invalid": "Введите имя и фамилию — минимум 2 слова.",
        "ask_phone": "Отправьте номер телефона кнопкой ниже:",
        "share_phone": "📱 Отправить номер телефона",
        "phone_invalid": "Используйте кнопку «Отправить номер телефона».",
        "ask_email": "Введите ваш email:",
        "email_invalid": "Email выглядит некорректно. Попробуйте ещё раз.",
        "ask_city": "Выберите город работы:", "city": "📍 Варшава",
        "success": "Спасибо! Ваша заявка отправлена. Менеджер свяжется с вами.",
        "already": "Вы уже отправляли заявку. Хотите заполнить новую?",
        "again": "🔄 Заполнить снова", "cancel": "Отмена",
        "cancelled": "Предыдущая заявка оставлена без изменений.",
        "error": "При отправке произошла ошибка. Попробуйте позже.",
    },
    "en": {
        "welcome": "Hello! Complete this short form and our manager will contact you.",
        "ask_name": "Enter your first and last name:",
        "name_invalid": "Enter at least two words: first and last name.",
        "ask_phone": "Share your phone number using the button below:",
        "share_phone": "📱 Share phone number",
        "phone_invalid": "Use the “Share phone number” button.",
        "ask_email": "Enter your email address:",
        "email_invalid": "The email address looks invalid. Please try again.",
        "ask_city": "Select the city where you want to work:", "city": "📍 Warsaw",
        "success": "Thank you! Your application has been sent. Our manager will contact you.",
        "already": "You have already submitted an application. Submit a new one?",
        "again": "🔄 Submit again", "cancel": "Cancel",
        "cancelled": "Your previous application was left unchanged.",
        "error": "An error occurred while sending the application. Please try again later.",
    },
}
LANGUAGE_NAMES = {"pl": "Polski", "ua": "Українська", "ru": "Русский", "en": "English"}
def t(language: str, key: str) -> str:
    return TEXTS.get(language, TEXTS["ru"]).get(key, key)
